identity:
  name: pie_chart
  author: Dify
  label:
    en_US: Pie Chart
    zh_Hans: 饼图
  icon: icon.svg
description:
  human:
    en_US: Pie chart
    zh_Hans: 饼图
  llm: generate a pie chart with input data
parameters:
  - name: data
    type: string
    required: true
    label:
      en_US: data
      zh_Hans: 数据
    human_description:
      en_US: data for generating pie chart
      zh_Hans: 用于生成饼图的数据
    llm_description: data for generating pie chart, data should be a string contains a list of numbers like "1,2,3,4,5"
    form: llm
