blank_issues_enabled: false
contact_links:
  - name: "\U0001F4E7 Dify Community"
    url: https://github.com/langgenius/dify/discussions/categories/general
    about: General discussions and request help from the community
  - name: "\U0001F4DA Dify user documentation"
    url: https://docs.dify.ai/getting-started/readme
    about: Documentation for users of Dify
  - name: "\U0001F4DA Dify dev documentation"
    url: https://docs.dify.ai/getting-started/install-self-hosted
    about: Documentation for people interested in developing and contributing for Dify
