name: Run Tool Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: ./api/requirements.txt

      - name: Install dependencies
        run: pip install -r ./api/requirements.txt

      - name: Run pytest
        run: pytest ./api/tests/integration_tests/tools/test_all_provider.py
